### ISSUE TITLE
Some conflicts of gene symbol

### ISSUE THREAD

**Issue by zhumengyan** [saezlab/dorothea#12]
Thanks for your interesting tools.
I found some conflicts of gene symbol in the provided human regulons. For example, BHLHE40, and its previous HGNC symbols STRA13 / BHLHB2 can all be found in regulons.

**Comment by christianholland** [comment]
Dear @zhumengyan,

thanks for pointing to this problem. I will check it and try to update all gene symbols to their latest version.

Thanks,
Christian
