### ISSUE TITLE
Question on mRNA expression versus DoRothEA TF activity

### ISSUE THREAD

**Issue by cswoboda** [saezlab/dorothea#18]
Hello!

Recently I applied your package to some single cell data. We have a transcription factor that has relatively high and specific expression in a subset of cells. However, after I apply the package, the resulting heatmap tells me that this population actually has the lowest expression of the transcription factor. Is the package working as it should, or am I misinterpreting the heatmap output or the algorithm? 

Thanks,

Casey

**Comment by christianholland** [comment]
Dear @cswoboda,

we are confident that the package works as expected. 

First of all it is certainly possible that you find the TF itself highly expressed but with a low predicted activity. High expression alone does not automatically cause a high activity, as the activity of a TF (or protein in general) is determined by many other factors such as post translational modification. 

As dorothea infers TF activities by interrogating the expression of the TF targets, I would recommend to check the expression of the targets of your TF of interest in the subset of cells. There you should find the answer why the TF activity is predicted lowly

**Comment by cswoboda** [comment]
Thank you for the response! I've been applying this package to a variety of different datasets we have and its been incredibly useful so far! I just wanted to make sure I wasn't misinterpreting the output, out of the excitement of an unexpected result.

Thanks!

Casey

**Comment by cswoboda** [comment]
Thank you for the response! I've been applying this package to a variety of different datasets we have and its been incredibly useful so far! I just wanted to make sure I wasn't misinterpreting the output, out of the excitement of an unexpected result.

Thanks!

Casey

**Comment by cswoboda** [comment]
Thank you for the response! I've been applying this package to a variety of different datasets we have and its been incredibly useful so far! I just wanted to make sure I wasn't misinterpreting the output, out of the excitement of an unexpected result.

Thanks!

Casey
