### ISSUE TITLE
database for TCGA samples

### ISSUE THREAD

**Issue by lxw391** [saezlab/dorothea#19]
Hi, 

In your paper "Benchmark and integration of resources for the estimation of human transcription factor activities" you mentioned 
"These resources are available in OmniPath (Türei et al. 2016; www.omnipathdb .org) and at https://saezlab.github.io/DoRothEA/. The normal collection comprises 1,077,121 TF–target candidate regulatory interactions between 1402 TFs and 26,984 targets. The pancancer collection includes 636,753 TF–target candidate regulatory interactions between 1412 TFs and 26,939 targets".

Is the dataset "dorothea_hs" derived from normal samples or cancer samples? where can we download the TF-target interactions for pancancer samples? 

Thanks!

**Comment by christianholland** [comment]
Hi @lxw391,

the regulons in the objects "dorothea_hs" are based on GTEx normal samples. The equivalent to the dorothea package but with regulons derived from TCGA are available here as R object: https://github.com/saezlab/dorothea/blob/deprecated/data/TFregulons/consensus/Robjects_VIPERformat/pancancer/TOP10_pancancer_viperRegulon.rdata

**Comment by lxw391** [comment]
Great, thanks!

**Comment by lxw391** [comment]
Hi @christianholland 

<img width="1152" alt="Capture" src="https://user-images.githubusercontent.com/27868862/91209262-76952900-e6d9-11ea-9f03-c69a95446c1e.PNG">
