### ISSUE TITLE
Dorothea using "RNA" assay by default instead of providing the option to indicate the real assay to use.

### ISSUE THREAD

**Issue by enblacar** [saezlab/dorothea#27]
Dear Dorothea developers,

Digging into the code a little bit, I realised the following potential error in the code for `dorothea::run_viper()`, when applied to an object of class Seurat. 

```r
run_viper.Seurat <- function(input, regulons, options = list(), tidy = FALSE) {
  if (tidy) {
    tidy <- FALSE
    warning("The argument 'tidy' cannot be TRUE for 'Seurat' objects. ",
            "'tidy' is set to FALSE")
  }
  mat <- as.matrix(Seurat::GetAssayData(input, assay = "RNA", slot = "data"))
​
  tf_activities <- run_viper(mat, regulons = regulons, options = options,
                             tidy = FALSE)
​
  # include TF activities in Seurat object
  dorothea_assay <- Seurat::CreateAssayObject(data = tf_activities)
  Seurat::Key(dorothea_assay) <- "dorothea_"
  input[["dorothea"]] <- dorothea_assay
​
  return(input)
}
```
As you can see, when defining `mat` object, it is retrieving by default the `RNA` object, and the `data` slot. The `data` slot stores the normalized non-centered data, as far as I am aware of. Therefore, I assume the VIPER scores are meant to be run on normalized data.

Then, in the case of people deviating from the standard Seurat's vignette, for instance using the new normalization methodology they suggest (Regularised negative binomial regression, using SCTransform package, actually already integrated into the Seurat package), the assay will change from `RNA` to `SCT`. Then, the `data` slot from the `RNA` assay will still contain the raw counts, and those will be used in VIPER ([reference](https://github.com/satijalab/seurat/issues/2362#issuecomment-561310379)).

Then, I would highly suggest to implement an assay parameter, in the same way as in Progeny, to allow the user to select the assay on which they have stored the normalized data (also, in the case the user, for any given reason, has modified the assay name).

This is how I modified it to take any slot desired:

```r
run_viper <- function(input, 
                          regulons, 
                          options = list(), 
                          tidy = FALSE,
                          assay.use = assay.use) {
        UseMethod("run_viper")
    }
    run_viper.Seurat <- function(input, 
                                 regulons, 
                                 options = list(), 
                                 tidy = FALSE,
                                 assay.use = "RNA") {
        if (tidy) {
            tidy <- FALSE
            warning("The argument 'tidy' cannot be TRUE for 'Seurat' objects. ",
                    "'tidy' is set to FALSE")
        }
        
        mat <- as.matrix(Seurat::GetAssayData(input, assay = assay.use, slot = "data"))
        
        tf_activities <- dorothea::run_viper(mat, regulons = regulons, options = options,
                                   tidy = FALSE)
        
        # include TF activities in Seurat object
        dorothea_assay <- Seurat::CreateAssayObject(data = tf_activities)
        Seurat::Key(dorothea_assay) <- "dorothea_"
        input[["dorothea"]] <- dorothea_assay
        
        return(input)
    }
```

Best,
Enrique

**Comment by christianholland** [comment]
Hi @enblacar,

thanks for this hint.  I just implemented this feature
