### ISSUE TITLE
Retrieve genes used for TF ID

### ISSUE THREAD

**Issue by SuFuBel** [saezlab/dorothea#30]
Dear Dorothea's team,
Is it possible to obtain a list of the genes from the input data that have been used to identify a determined TF in each cell (or cluster)?
Thanks for such a good tool,
Cheers

**Comment by christianholland** [comment]
Dear @SuFuBel,

thanks for your message.

If I understand you correctly you would like to obtain the genes that contributed to the activity score of a TF, wouldn't you? As viper is a rank-based (i.e. viper ranks for each sample/cell/cluster genes) approach all genes of your input contribute to the ranking and thus to the activity score.

Still you could compute the overlap between the target genes of a specific TF and the genes in the gene expression matrix, which would tell you how many target genes you actually cover in your experiment.

Does this answer your question?

Best wishes,
Christian

**Comment by SuFuBel** [comment]
Thank you for your reply and suggestion. I will do that, thanks again.

Cheers
________________________________
