### ISSUE TITLE
df2regulon function returns list instead of regulon object

### ISSUE THREAD

**Issue by justinjacobse** [saezlab/dorothea#32]
Dear developers,

I'm trying to run msVIPER on a DESeq2 dataset. With converting the dorothea regulons to a format suitable for msVIPER, I run into the problem that the output of the code below (thanks Christian for pointing me to this function) is a list, and not a regulon object. Could you please help me further?

```
# Load dorothea
library("dorothea")
# Load mm data from dorothea
data(dorothea_mm, package ="dorothea")
# Convert to the format required by viper
viper_regulons <- dorothea::df2regulon(dorothea_mm)
```

Thanks,
Justin

**Comment by christianholland** [comment]
Hi Justin,

in order to help you I would need to additional information:

i ) Which dorothea version are you using?
ii) Could you please copy and paste the entire error message?

**Comment by justinjacobse** [comment]
Thanks Christian, than my problem must lie somewhere in viper, I will go have a look at what's going on there.
