### ISSUE TITLE
TF Enrichment Scores

### ISSUE THREAD

**Issue by jamrute** [saezlab/dorothea#33]
Thank you for developing this great tool!

For the TF enrichment scores from (`https://bioconductor.org/packages/release/data/experiment/vignettes/dorothea/inst/doc/single_cell_vignette.html#introduction`) do positive values mean positive enrichment and negative values mean negative enrichment of the respective TFs?

I am trying to take the ratio of TF enrichment scores for two different cell types and want to understand how best to do this/interpret the results.

**Comment by christianholland** [comment]
Hi @jamrute,

indeed a positive enrichment score means that the target genes of your TF are enriched at the top ranks of your expression profile and vice versa. 

Just a small idea what you can try if you would want to find differences in TF activity between cell types. Assuming you have a Seurat object you can directly run the `run_viper()` function on your object. Then you can change the assay to `dorothea`, set the identities to your cell types and run `FindAllMarkers()`. This will return you a list of differentially activated TFs. Same workflow is for sure also possible if you are working with the `SingleCellExperiment` object.

**Comment by jamrute** [comment]
Thank you @christianholland . This was an interesting idea, and I ran the Find All Markers DGE using the Viper scores.
