### ISSUE TITLE
Preprocessing for Bulk RNA-Seq

### ISSUE THREAD

**Issue by MikhaelManurung** [saezlab/dorothea#34]
Dear authors,

Thank you for making such an easy-to-use package. What is the recommended preprocessing for bulk RNA-Seq data?

Thanks in advance.

**Comment by christianholland** [comment]
Hi @MikhaelManurung,

thanks for your kind words. We mostly use the `edgeR` package for filtering out lowly expressed genes  and TMM normalisation. With` limma:voom()` we transform the data to `logCPM`. However, alternative approaches such as from `DESeq2` will work as well.

**Comment by MikhaelManurung** [comment]
Thank you for your response!
