### ISSUE TITLE
Integration of regulon activities across different datasets

### ISSUE THREAD

**Issue by GMFranceschini** [saezlab/dorothea#39]
Dear authors, thank you for developing dorothea, I am excited to use it for my research.
I would like to ask a question concerning the integration of different datasets to compare regulon activities, I hope this is the right place.

Besides merging all the data during the upstream processing, is there a strategy to compare the NES obtained in a dataset with another one? Something tells me that I cannot directly do that, can you confirm?
 
For instance, I found the regulons reported in https://dorothea.opentargets.io/#/ very useful, and I would like to measure and compare regulons the activity in another set of samples (and then for example find the most similar cell line). But let's suppose I now measure the same regulons on a set of immune cells, could I integrate the NES of those two sources? What would be your recommendation to achieve that, possibly starting from processed data?

**Comment by christianholland** [comment]
Hi @GMFranceschini, please apologise the delayed reply. Following the vignette the `run_viper()`function scales the expression matrix. This makes two independent matrices of NES hardly comparable. To make them directly comparable I recommend to merge all data before computing the NES.

**Comment by GMFranceschini** [comment]
Thank you, Christian. So you suggest integrating counts data and run the analysis of the full set. That was more of a `viper` question probably, sorry for that. Closing the issue, feel free to reopen if you ever stumble upon another strategy!
