### ISSUE TITLE
A question about Regulon format

### ISSUE THREAD

**Issue by andreyurch** [saezlab/DoRothEA#4]
Dear developers,

Is there a way to make a regulon object based on my specific set of TF and their targets? 

Thank you!

**Comment by christianholland** [comment]
Dear user,

thanks for your question. 
Yes, this is possible. However, there is no dedicated function for this and of course the required steps depends on your current data format. If you want to provide your current format I can help you with converting it to a regulon object.

Best,
Christian

**Comment by andreyurch** [comment]
Dear Christian,

Thank you for your reply!  I like very much the Dorothea idea and database. I actually take the regulons from your repository http://saezlab.org/tfregulons/  and format it removing some interactions or adding them (activation, repression).  So, it would be great to find a way to convert from this format or from https://github.com/saezlab/DoRothEA/tree/master/data/TFregulons/consensus/table to VIPER. 

By the way, can I ask what is the publication stage of your paper https://www.biorxiv.org/content/10.1101/337915v2 ?   

Best,
Andrey

**Comment by christianholland** [comment]
Hi Andrey,
you can use the function df2regulon() which you find [here](https://github.com/saezlab/ConservedFootprints/blob/3cee21853a90f78bd13b6eebcb5538fc4c129cab/src/dorothea_analysis.R#L105-L120).
This function was designed to transform regulons stored as data frame to the required viper format. The data frame must exclusively contain the following columns: tf, target, mor, likelihood. Please let me know if something doesn't work.

The paper is in second revision, so we hope that it will be published very soon.

Best,
Christian
