### ISSUE TITLE
access to dorothea_hs?

### ISSUE THREAD

**Issue by algarji** [saezlab/dorothea#41]
Hi, maybe it is an obvious question, but is there any mode to access to dorothea_hs dataset (containing TF-target interactions with confidence levels and A-E scoring)? It would be interesting for me to explore what genes are taken in consideration to define the significant regulons found in a sc experiment.  Thanks.

**Comment by christianholland** [comment]
Hi @algarji,

you can access the dorothea_hs object with `data(dorothea_hs, package = "dorothea")`

Best wishes,
Christian

**Comment by algarji** [comment]
Great, thank you @christianholland
