### ISSUE TITLE
Trace back the evidence

### ISSUE THREAD

**Issue by shokohirosue** [saezlab/dorothea#45]
Thank you for developing a great package.

I have a specific TF of interest, and would like to know what evidence the interactions are based on. (Which ChIP seq data, which paper etc...) Would this be possible? 

Thank you so much for your help!

**Comment by christianholland** [comment]
Hi @shokohirosue,

yes, this is possible. Please check in an R session the object `dorothea::entire_database`. This data contains information that allow to trace back the origin of every TF-target interaction.

**Comment by shokohirosue** [comment]
Thank you!
