### ISSUE TITLE
Calculating TF scores and inference on SEURAT clusters

### ISSUE THREAD

**Issue by EAC-T** [saezlab/dorothea#46]
Hi everyone,

Thank you a lot for the package, 
I followed the tutorial where we re-did the clustering with TF, 
I got interesting results however I want to keep my initial SEURAT clustering and do the TF activity score and the rest on them,

How would I do that? 

Thank you a lot,

**Comment by christianholland** [comment]
Hi, 

please apologise but I am not a Seurat expert. Intuitively I would recommend to store the active Identities `Idents(object)` you got from clustering in the meta data slot `object@meta.data`. So you would end up with two cell type annotations. One from clustering based on gene expression and the other based on TF activities.

I hope this helps

**Comment by EAC-T** [comment]
Hi @christianholland ,
Ok, It's just that the tutorial I think was structured around reclustering based on TF which is interesting. If I skip this part, and go to the next section "TF activity per cell population" I should be able to do it right? is there a way to visualize a TF on top of the umap instead of using a heatmap? 
Sorry, I'm very new to coding and trying to find my way though

Thank you a lot

**Comment by christianholland** [comment]
Yes there are several ways for instance box/violoin plots or general bar plots. I can recommend to check this website https://www.data-to-viz.com to get an overview of which type of visualisation is suitable for your data.

**Comment by EAC-T** [comment]
@christianholland , sorry to bother you again, I did what you said and when I got to this step:
viper_scores_df <- GetAssayData(pbmc, slot = "scale.data",   assay = "dorothea") %>%
  data.frame(check.names = F) %>%
  t()

it didn't work, the scale.data slot is empty, I had to chose slot="data",

would you know why? should I scale it somehow for downstream analysis?

Thank you,
