### ISSUE TITLE
No bug, just a question :-)

### ISSUE THREAD

**Issue by aldojongejan** [saezlab/dorothea#55]
I am trying to redo an analysis from a paper. Here the state to have selected the TF with highest confidence from Dorothea and they end up with 168 TFs (and 2602 unique targets). Working with the latest version under R 4.1 I could find 96 for confidnce level A and 22 for B, only adding up to 118. Adding level C would give 271... I also tried with dorothea v1.0.0, but that gave me roughly the same numbers. Do you have any idea which version they have been using? Where can I obtain older versions of dorothea?
Thanks in advance!!
Aldo

**Comment by christianholland** [comment]
Hi @aldojongejan,

`Do you have any idea which version they have been using?` - To answer this question we would need to know which publication you are referring to.

Best,
Christian

**Comment by aldojongejan** [comment]
Hi Christian,
I am referring to the paper by Lopez-Dominguez et al. https://www.mdpi.com/2075-1729/11/4/299. But let me ask them directly first before you are going to spend time on it :-) 
I was just hoping you kept some kind of stats on how the TF-database evolved.. Thanks for your fast reply!!
With kind regards,
Aldo

**Comment by christianholland** [comment]
Alright, good luck with your project

**Comment by aldojongejan** [comment]
Dear Christian,

Finally had a chance to get back to this project... :-) 
Did not get any answer from the authors, so if you by any chance would have some time to look into my original question, I would appreciate it!

with kind regards,
Aldo

**Comment by christianholland** [comment]
Hi Aldo,

sorry to hear that you didn't get any reply. You could access older versions of dorothea from the Bioconductor archive. Given that the paper was submitted in January 2021 I would assume the authors used the version `1.0.0` but please note that this is only a guess

**Comment by aldojongejan** [comment]
Dear Christian,

Thank you for your reply!
I did check that version, as I had the same thought, but that did not work for me....

Thanks for your help, regards,
Aldo
