### ISSUE TITLE
No dataframe output when I try to generate Viper score per cell and clusters

### ISSUE THREAD

**Issue by sylestiel** [saezlab/dorothea#66]
Hi @mschubert 

<img width="449" alt="Screen Shot 2023-02-16 at 11 56 27 AM" src="https://user-images.githubusercontent.com/64283689/219448597-6bcad440-497b-45e7-8a79-e5c7dcd7f802.png">

Has the screen shot shows I cannot create a data frame with the Viper score per cell and its clusters. What can I alter to get this working. This is with respect to a mouse dataset.

Appreciate your help/suggestions troubleshooting this issue.

Thanks!

**Comment by dbdimitrov** [comment]
Hi @sylestiel,

Not sure if Michael will answer, so I'll have to suffice.

Without an example in which you show how you encounter this issue, there is little that I can do. Can you please provide one?

Also, dorothea's enrichment methods have been deprecated in favour of decoupleR, see single-cell tutorial /w dorothea here: https://saezlab.github.io/decoupleR/articles/tf_sc.html

Hope this helps,
Daniel
