### ISSUE TITLE
Question regarding input into run_viper()

### ISSUE THREAD

**Issue by ashaypatel** [saezlab/dorothea#67]
Hello, I am using the  DoRothEA package for bulk rna-seq analysis. I have been working with the DESeq2 package. Can I use vst normalized data for the input argument in run_viper, or does the input have to be non-transformed, non pre-filtered counts?

Thanks

**Comment by dbdimitrov** [comment]
Hi @ashaypatel,

Using normalized data is usually the way to go.

Hope this helps.
Daniel
